In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mplcursors

In [134]:
try:
    data = pd.read_csv("/Volumes/B/Downloads/Experiments Summary - Sheet1 (5).csv", delimiter=",")#,nrows=10000)#,nrows=10000
    print(" dataset has {} samples with {} features each.".format(*data.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 349 samples with 13 features each.


In [135]:
data = data.dropna(how='all')
data.head()

Rounds                      Metrics  WA_All_par_1  WA_All_par_2  \
1     0.0    Simulation Time (minutes)     27.390000  1.494000e+01   
2     0.0  Projected Convergence Score      0.027585  2.017607e-02   
3     0.0               Binary DICE WT      0.060016  5.710000e-13   
4     0.0               Binary DICE ET      0.009464  3.435366e-02   
5     0.0               Binary DICE TC      0.013276  2.617455e-02   

   WA_col10_part_1  WA_col10_part_2  WA_col20_part_2  WA_col50_part_2  \
1        10.160000         5.310000     9.930000e+00        14.940000   
2         0.023772         0.181144     1.437384e-01         0.093129   
3         0.000002         0.503604     2.194941e-01         0.050958   
4         0.054206         0.017679     4.460000e-11         0.011833   
5         0.017109         0.022148     2.117210e-01         0.216597   

   WA_col10_part_3  ESA_All_par_1  CTA_All_par_1_Thr_0.35  \
1        11.260000      27.390000               27.390000   
2         0.031114       0.023516                0.013332   
3         0.083451       0.041143                0.000063   
4         0.006555       0.014615                0.000872   
5         0.003336       0.014792                0.039061   

   CTA_10_par_1_Thr_0.35  CTA_10_par_2_Thr_0.35  
1               8.670000              11.330000  
2               0.033436               0.131824  
3               0.099057               0.000252  
4               0.000980               0.033958  
5               0.000272               0.361263

In [136]:
#myarray = ['WA_All_par_1','WA_All_par_2','WA_col10_part_1','WA_col10_part_2','WA_col20_part_2','WA_col50_part_2','WA_col10_part_3','ESA_All_par_1','CTA_All_par_1_Thr_0.35']
myarray = ['CTA_10_par_2_Thr_0.35']


In [137]:
for c in myarray:
    

    data1 = data[['Rounds','Metrics',c]].dropna()
    data1.head()

    data1= data1.pivot(index='Rounds', columns='Metrics', values=c).reset_index().rename_axis(columns=None)
    data1.dropna(how='all')
    data1.head()

    data1['Simulation Time (minutes)'] = data1['Simulation Time (minutes)'].div(60).round(2)
    #data1

    %pylab

    fig, axs = plt.subplots(8, sharex=True, sharey=False)#subplot_kw=dict(projection='polar')
    fig.set_size_inches(10, 8)
    #texts('WA_All_par_1')
    axs[0].plot(data1['Rounds'], data1['Binary DICE WT'], color='red')
    axs[0].set_xlabel('Rounds')
    axs[0].set_ylabel("DWT")
    #axs[0].set_ylim([0.,0.5])

    axs[1].plot(data1['Rounds'], data1['Binary DICE ET'], color='blue')
    axs[1].set_xlabel('Rounds')
    axs[1].set_ylabel("DET")
    #axs[1].set_ylim([0.,70])

    axs[2].plot(data1['Rounds'], data1['Binary DICE TC'], color='pink')
    axs[2].set_xlabel('Rounds')
    axs[2].set_ylabel("DTC")

    axs[3].plot(data1['Rounds'], data1['Hausdorff95 WT'], color='cyan')
    axs[3].set_xlabel('Rounds')
    axs[3].set_ylabel("HWT")

    axs[4].plot(data1['Rounds'], data1['Hausdorff95 ET'], color='olive')
    axs[4].set_xlabel('Rounds')
    axs[4].set_ylabel("HET")

    axs[5].plot(data1['Rounds'], data1['Hausdorff95 TC'], color='purple')
    axs[5].set_xlabel('Rounds')
    axs[5].set_ylabel("HTC")

    axs[6].plot(data1['Rounds'], data1['Projected Convergence Score'], color='green')
    axs[6].set_xlabel('Rounds')
    axs[6].set_ylabel("Score")

    axs[7].plot(data1['Rounds'], data1['Simulation Time (minutes)'], color='brown')
    axs[7].set_xlabel('Rounds')
    axs[7].set_ylabel("Time")

    #axs.set_title('Title')
    mplcursors.cursor(hover=True)
    #c+'.png'
    #plt.savefig("CTA_All_par_1_Thr_0.35.png")
    plt.show()

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [8]:
data2 = data[['Rounds','Metrics','WA_All_par_1']].dropna()

data2.head()

Rounds                      Metrics  WA_All_par_1
1     0.0    Simulation Time (minutes)     27.390000
2     0.0  Projected Convergence Score      0.027585
3     0.0               Binary DICE WT      0.060016
4     0.0               Binary DICE ET      0.009464
5     0.0               Binary DICE TC      0.013276

In [9]:
#data2['Simulation Time (minutes)'] = data2['Simulation Time (minutes)'].div(60).round(2)
data2['WA_All_par_1'] = np.where(data2['Metrics'].eq('Simulation Time (minutes)'),
                              data2['WA_All_par_1'] / 60, 
                              data2['WA_All_par_1'])
data2

Rounds                      Metrics  WA_All_par_1
1       0.0    Simulation Time (minutes)      0.456500
2       0.0  Projected Convergence Score      0.027585
3       0.0               Binary DICE WT      0.060016
4       0.0               Binary DICE ET      0.009464
5       0.0               Binary DICE TC      0.013276
..      ...                          ...           ...
154    15.0               Binary DICE ET      0.831129
155    15.0               Binary DICE TC      0.871030
156    15.0               Hausdorff95 WT      4.391631
157    15.0               Hausdorff95 ET      2.196835
158    15.0               Hausdorff95 TC      2.462551

[128 rows x 3 columns]

In [10]:
%pylab
(data2.set_index(['Rounds','Metrics'])
 .unstack(1)
 .droplevel(0,axis=1)
 .sort_index(1,ascending=False)
 .plot(figsize=(15,5),kind='bar',legend=True))
mplcursors.cursor(hover=True)

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [83]:
!pwd

/Volumes/B/Basecamp/FL_Step_by_Step_Implementation_in_Tensorflow/MICCAI_FeTS2021_TrainingData


In [10]:
import random
percentage = 0.1
for i in range(5):
    collaborators = [3,6,9,8,7,1,2,4,5,19,10,11,12,13,14,15,16,17,18,20]
    random.sample(range(len(collaborators)), int(max(1,percentage * len(collaborators))))

[8, 14]

In [11]:
import random
percentage = 0.1
desired_length = 5
my_array = [3,6,9,8,7,1,2,4,5,19,10,11,12,13,14,15,16,17,18,20]
random.sample(range(len(my_array)), int(max(1,percentage * len(my_array))))

[15, 12]

In [13]:
my_array[:desired_length]

[3, 6, 9, 8, 7]

In [46]:
import random
percentage = 0.1
desired_length = 5
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in range(5):
    print(random.sample(range(len(my_array[desired_length-1:desired_length])), int(max(1,percentage * len(my_array[desired_length-1:desired_length])))))
    desired_length = desired_length + 5

[0]
[0]
[0]
[0]


ValueError: Sample larger than population or is negative

In [45]:
my_array[desired_length-5:desired_length]

[]

In [41]:
my_array[10:15]

[11, 12, 13, 14, 15]

In [47]:
for i in range(5):
    print(i)

0
1
2
3
4


In [48]:
import random
percentage = 0.1
desired_length = 5
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(random.sample(range(len(my_array[:])), int(max(1,percentage * len(my_array[:])))))

import numpy as np
chunks = np.array_split(my_array, 5)
chunks

[9, 13]


[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19, 20])]

In [51]:
percentage = 0.5

for chunk in chunks:
    print(random.sample(range(len(chunk)), int(max(1, percentage * len(chunk)))))

[3, 2]
[2, 0]
[1, 2]
[3, 0]
[3, 2]


In [54]:
import numpy as np
percentage = 0.5
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 21, 22, 23, 24, 25]

chunks = np.array_split(my_array, 5)
selected_items = [random.sample(list(chunk), int(max(1, percentage * len(chunk)))) for chunk in chunks]

In [55]:
selected_items

[[2, 5], [10, 9], [13, 14], [18, 17], [21, 22]]

In [73]:
import numpy as np
percentage = 0.5
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 21, 22, 23, 24, 25]
fl_round = 3
chunks = np.array_split(my_array, fl_round)
selected_items = [random.sample(list(chunk), int(max(1, percentage * len(chunk)))) for fl_round in chunks]

In [74]:
selected_items

[[18, 17], [20, 19], [20, 19]]

In [84]:
import numpy as np
chunks = np.array_split(my_array, 5)
for i, chunk in enumerate(chunks):
    selected_items = random.sample(list(chunk), int(max(1, percentage * len(chunk))))
    print ("iteration ", i+1, ": ", selected_items)
    # do stuff with selected_items

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [83]:
my_array

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [87]:
import Math
print(Math.floor((my_array.length-1) * percentage))

ModuleNotFoundError: No module named 'Math'

In [96]:
my_array[0:int(len(my_array)*percentage)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [98]:
for i in range(0, len(my_array), int(len(my_array)*percentage))

SyntaxError: invalid syntax (<ipython-input-98-0ea18ff0ffc1>, line 1)

In [128]:
import numpy as np
chunks = np.array_split(my_array, 5)
for i, chunk in enumerate(chunks):
    selected_items = random.sample(list(chunk), int(max(1, percentage * len(chunk))))
    print ("iteration ", i+1, ": ", selected_items)
    # do stuff with selected_items

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [119]:
percentage = 0.2
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

windowsize = (len(my_array)*percentage)
if windowsize.is_integer():     
    for i in range(0, len(my_array), int(windowsize)):
        print(my_array[i: i+int(windowsize)]) 
else:     
    print('Can not divide in equal chunk') 

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]
[17, 18, 19, 20]


In [106]:
percentage

0.5

In [107]:
windowsize

12.5

In [129]:
percentage = 0.2
my_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24]

windowsize = (len(my_array)*percentage)    
for i in range(0, len(my_array), int(windowsize)):
    print(my_array[i: i+int(windowsize)]) 


[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]
[17, 18, 19, 20]
[21, 23, 24]


In [131]:
shuffle(my_array)
windowsize = (len(my_array)*percentage)    
for i in range(0, len(my_array), int(windowsize)):
    print(my_array[i: i+int(windowsize)]) 

[9, 14, 16, 3]
[21, 10, 24, 6]
[19, 4, 1, 17]
[18, 7, 5, 2]
[13, 15, 8, 11]
[23, 20, 12]
